### PR TITLE
Removed stop kwarg from I2CDevice.reads, moved to write_then_readinto

### LINKED ISSUE #5: Adafruit BusDevice error when reading anything
Looks like Adafruit I2C Device class no longer supports `stop` in write functions.  Needs to be removed.  Will look at a pull request as soon as testing is successful.

### PR DESCRIPTION
**Pull request by fivesixzero**
Fixes #5 by moving to the newer `I2CDevice` model of using `write_then_readinto` for reading registers into buffers.

### CODE REVIEW

**Comment by fivesixzero** [comment]
For good measure I fixed some typos and added type hints and some typing fixes for booleans in 2f852bc and 8caa5a7.

**Comment by fivesixzero** [comment]
Just realized that @imandel submitted #6 with a prospective fix for this issue at the beginning of the year. Definitely take a look at that PR while reviewing this one.

I think the shift to `write_then_readinto` is more comprehensive than just removing the kwarg but I'll be happy to close this PR if the approach in that PR is preferred.

**Review by fourstix — COMMENTED** [review]
Looks good.  Thank you for all the other clean up work that you did.

**Comment by fivesixzero** [comment]
@fourstix Happy to help! Thanks for taking a look and getting it merged in and, of course, taking the time to maintain this stuff. <3

**Pull request merged**
